services:
  - type: web
    name: goxstream
    env: node
    plan: free
    autoDeploy: false
    buildCommand: pnpm run build:render
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: 22
