// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	COMMENTS: DurableObjectNamespace /* CommentRoom */;
	R2: R2Bucket;
	DB: D1Database;
	VIEWS: AnalyticsEngineDataset;
	AI: Ai;
	ASSETS: Fetcher;
}
