// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	DATABASE_URL: string;
	COMMENTS: DurableObjectNamespace<import("./.output/server/index").CommentRoom>;
	R2: R2Bucket;
	DB: D1Database;
	VIEWS: AnalyticsEngineDataset;
	AI: Ai;
	ASSETS: Fetcher;
}
