#:schema node_modules/wrangler/config-schema.json
name = "zenith"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "R2"
bucket_name = "anistream-media"
preview_bucket_name = "anistream-media"

[[kv_namespaces]]
binding = "KV"
id = "d4630f91cdd841eb990c6efef66a07dc"
preview_id = "d4630f91cdd841eb990c6efef66a07dc"


[[analytics_engine_datasets]]
binding = "VIEWS"
dataset = "zenith_views"