name = "zenith-stream-signer"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "anistream-media"

[vars]
SUPABASE_URL = "https://txvfsitiihskzbjkulus.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpaWhza3piamt1bHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1MTk1NjEsImV7aawnMjAOum_qMTE2MX0.JsWiReftuab9PoGWKItsZ1I1Hv0Fp7aawn-__Oum_qMTE2MX0.JsWiReftuab9PoGWKItsZ1I1Hv0Fp7aawn-__Oum_qM"
